### ISSUE TITLE
Exclude whole folder?

### ISSUE THREAD

**Issue by JakubSledz** [kamilstanuch/codebase-digest#1]
Is it possible to exclude a folder?

**Comment by kamilstanuch** [comment]
Good point!
Only files so far but will add option to exclude folders (env etc.) - makes
sense!

--ignore-ext: Additional file extensions to ignore (e.g., .pyc .log).



Kamil Stanuch

Newsletter: https://kamilstanuch.pl/friendzone/
LinkedIn: https://www.linkedin.com/in/kamilstanuch/
Twitter: https://twitter.com/KamilStanuch


W dniu śr., 9.10.2024 o 15:38 JakubSledz ***@***.***>
napisał(a):

**Comment by kamilstanuch** [comment]
Yes, now in v. 0.1.40 it's possible to exclude a folder and even more. Here's how you can do it:

**1. Using the command line:**
   You can use the `--ignore` option to exclude specific folders. For example:

   ```
   cdigest /path/to/your/project --ignore "folder_to_exclude"
   ```

   This will ignore the "folder_to_exclude" directory and all its contents.

**2. Using a .cdigestignore file:**
   For a more permanent solution, you can create a `.cdigestignore` file in your project's root directory. In this file, you can list all the folders and files you want to exclude. For example:

   ```
   # .cdigestignore
   folder_to_exclude
   another_folder_to_exclude
   ```

   Codebase Digest will automatically read this file and ignore the specified folders.

You can also use patterns. For example, to ignore all folders that start with "temp_", you could use:

`cdigest /path/to/your/project --ignore "temp_"`


I hope this helps! Let me know if you have any more questions or suggestions :)
